Feature/create product article
PolyMarket-Team/polymarket-backend pull request #26
Opened 2022-05-30 05:13 UTC by minjun7984

상품등록 및 상품조회 API 구현했습니다
상품 등록시 indexOf 를 통해 순서대로 파일시퀀스 값을 부여했습니다.

2022-05-30 14:09 UTC, siru-dduck requested changes

2022-05-30 14:09 UTC, siru-dduck commented on src/main/java/kr/polymarket/domain/product/dto/CreateProductArticleDto.java
> +public class CreateProductArticleDto {
현재 우리가 사용자의 요청을 매핑할때 쓰는 객체를 ~RequestDto 접미사로 쓰고있는데 이거에 맞게 코드 컨밴션을 유지해야하지 않을까 싶네, 사실 우리 둘이서 코드를 작성하기에 우리 둘간의 협의가 필요할거 같아

2022-05-30 14:09 UTC, siru-dduck commented on src/main/java/kr/polymarket/domain/product/dto/ProductArticleDetailDto.java
> +public class ProductArticleDetailDto {
응답 객체에 스웨거 설명을 추가해주고, 이것도 네이밍을 ~ResponseDto 혹은 ~ResultDto등으로 해야할거 같은데 네이밍 관련해서 확실히 픽스해야할거같아

2022-05-30 14:09 UTC, siru-dduck commented on src/main/java/kr/polymarket/domain/product/service/ProductService.java
> +            throw new ProductNotFoundException();
로직이 지금 보면 ProductNotFoundException 예외에 대해서 69번 라인에서 jpa entity를 조회하면서 한번 72번 라인에서 검증을 하는데 72,73번 라인 지우고 `productRepository.findProductDetailById(Id)`호출시 jpql을 아래와 같이 하면 한방쿼리로 끝낼 수 있어
`@Query("select p from product p join fetch p.category join fetch p.productFileList join fetch p.user where p.id = :id and p.status != kr.polymarket.domain.product.entity.ProductStatus.DELETE")
    Optional<Product> findProductDetailById(Long id);`

2022-05-30 14:16 UTC, siru-dduck requested changes

2022-05-30 14:16 UTC, siru-dduck commented on src/main/java/kr/polymarket/domain/product/dto/CreateProductArticleDto.java
> +    private Integer categoryId;
카테고리 아이디를 직접 입력받는 경우 클라이언트 오류 가능성이 있고 카테고리의 경우 데이터를 서버쪽에서 반영을 하고 관리하니까 

```java
@Getter
@RequiredArgsConstructor
public enum ProductCategory {
    USED_CAR("C01", "중고차", 1),
    DIGITAL_DEVICE("C01", "디지털기기", 2),
    HOME_APPLIANCES("C02", "생활가전", 3),
    FURNITURE_INTERIOR("C03", "가구/인테리어", 4),
    INFANT_CHILD("C04", "유아동", 5),
    LIFE_PROCESSED_FOOD("C05", "생활가전", 6),
    CHILDREN_BOOKS("C06", "유아도서", 7),
    SPORTS_LEISURE("C07", "스포츠/레저", 8),
    WOMEN_ACCESSORIES("C08", "여성잡화", 9),
    WOMEN_CLOTHING("C09", "여성의류", 10),
    MENS_FASHION_ACCESSORIES("C10", "남성패션/잡화", 11),
    GAME_HOBBY("C11", "게임/취미", 12),
    BEAUTY("C12", "뷰티/미용", 13),
    PET_SUPPLIES("C13", "반려동물용품", 14),
    BOOK_TICKET_ALBUM("C14", "도서/티켓/음반", 15),
    PLANT("C15", "식물", 16),
    ETC("C16", "기타중고물품", 17)
    ;

    private final String code;
    private final String value;
    private final Integer id;

}
```

Integer 타입으로 카테고리 아이디를 직접 입력받는게 아닌 enum 타입으로 받는게 어떤가 싶어 
아래 pr 파일중에 `ProductCategory.java` 파일 있는데 그거 확인해보면 좋을듯 공용으로 같이 써두 되고
https://github.com/PolyMarket-Team/polymarket-backend/pull/23/files

2022-05-30 14:41 UTC, siru-dduck commented on src/main/java/kr/polymarket/domain/product/service/ProductService.java
> +        });
이렇게 fileSequence 1인 이미지가 메인이미지(대표 썸네일 이미지)가 되는게 맞지? (확인차 물어본거)

2022-05-30 15:07 UTC, minjun7984 commented on src/main/java/kr/polymarket/domain/product/dto/CreateProductArticleDto.java
> +public class CreateProductArticleDto {
~RequestDto 접미사로 변경해서 컨벤션 유지하도록 변경하겠습니다

2022-05-30 15:08 UTC, minjun7984 commented on src/main/java/kr/polymarket/domain/product/dto/ProductArticleDetailDto.java
> +public class ProductArticleDetailDto {
네넵!!

2022-05-30 15:08 UTC, minjun7984 commented on src/main/java/kr/polymarket/domain/product/service/ProductService.java
> +        });
1번 이미지가 메인이미지가 되는거 맞습니다!

2022-06-02 08:38 UTC, siru-dduck approved these changes

2022-06-02 08:38 UTC, siru-dduck commented
approve 했습니다

2022-06-02 08:39 UTC, merged